name: next js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Go to source code directory
      run: cd /var/www/practice-ci-cd/
      run: git reset --hard
    - name: Repo Status
      run: git status
    - name: Add all the files
      run: git add .
    - name: Pull from repo
      run: sudo git pull origin main
    - name: Build
      run: npm run build
